// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'boxscore_advanced_team_stats.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

BoxscoreAdvancedTeamStats _$BoxscoreAdvancedTeamStatsFromJson(
        Map<String, dynamic> json) =>
    BoxscoreAdvancedTeamStats(
      json['assists'] as int?,
      (json['assistsTurnoverRatio'] as num).toDouble(),
      json['benchPoints'] as int?,
      json['biggestLead'] as int?,
      json['biggestLeadScore'] as String?,
      json['biggestScoringRun'] as int?,
      json['biggestScoringRunScore'] as String?,
      json['blocks'] as int?,
      json['blocksReceived'] as int?,
      json['fastBreakPointsAttempted'] as int?,
      json['fastBreakPointsMade'] as int?,
      (json['fastBreakPointsPercentage'] as num).toDouble(),
      json['fieldGoalsAttempted'] as int?,
      (json['fieldGoalsEffectiveAdjusted'] as num).toDouble(),
      json['fieldGoalsMade'] as int?,
      (json['fieldGoalsPercentage'] as num).toDouble(),
      json['foulsDrawn'] as int?,
      json['foulsOffensive'] as int?,
      json['foulsPersonal'] as int?,
      json['foulsTeam'] as int?,
      json['foulsTeamTechnical'] as int?,
      json['foulsTechnical'] as int?,
      json['freeThrowsAttempted'] as int?,
      json['freeThrowsMade'] as int?,
      (json['freeThrowsPercentage'] as num).toDouble(),
      json['leadChanges'] as int?,
      json['minutes'] as String?,
      json['minutesCalculated'] as String?,
      json['points'] as int?,
      json['pointsAgainst'] as int?,
      json['pointsFastBreak'] as int?,
      json['pointsFromTurnovers'] as int?,
      json['pointsInThePaint'] as int?,
      json['pointsInThePaintAttempted'] as int?,
      json['pointsInThePaintMade'] as int?,
      (json['pointsInThePaintPercentage'] as num).toDouble(),
      json['pointsSecondChance'] as int?,
      json['reboundsDefensive'] as int?,
      json['reboundsOffensive'] as int?,
      json['reboundsPersonal'] as int?,
      json['reboundsTeam'] as int?,
      json['reboundsTeamDefensive'] as int?,
      json['reboundsTeamOffensive'] as int?,
      json['reboundsTeamTotal'] as int?,
      json['secondChancePointsAttempted'] as int?,
      json['secondChancePointsMade'] as int?,
      (json['secondChancePointsPercentage'] as num).toDouble(),
      json['steals'] as int?,
      json['threePointersAttempted'] as int?,
      json['threePointersMade'] as int?,
      (json['threePointersPercentage'] as num).toDouble(),
      json['timeLeading'] as String?,
      json['timesTied'] as int?,
      (json['trueShootingAttempts'] as num?)?.toDouble(),
      (json['trueShootingPercentage'] as num).toDouble(),
      json['turnovers'] as int?,
      json['turnoversTeam'] as int?,
      json['turnoversTotal'] as int?,
      json['twoPointersAttempted'] as int?,
      json['twoPointersMade'] as int?,
      (json['twoPointersPercentage'] as num).toDouble(),
    );

Map<String, dynamic> _$BoxscoreAdvancedTeamStatsToJson(
        BoxscoreAdvancedTeamStats instance) =>
    <String, dynamic>{
      'assists': instance.assists,
      'assistsTurnoverRatio': instance.assistsTurnoverRatio,
      'benchPoints': instance.benchPoints,
      'biggestLead': instance.biggestLead,
      'biggestLeadScore': instance.biggestLeadScore,
      'biggestScoringRun': instance.biggestScoringRun,
      'biggestScoringRunScore': instance.biggestScoringRunScore,
      'blocks': instance.blocks,
      'blocksReceived': instance.blocksReceived,
      'fastBreakPointsAttempted': instance.fastBreakPointsAttempted,
      'fastBreakPointsMade': instance.fastBreakPointsMade,
      'fastBreakPointsPercentage': instance.fastBreakPointsPercentage,
      'fieldGoalsMade': instance.fieldGoalsMade,
      'fieldGoalsEffectiveAdjusted': instance.fieldGoalsEffectiveAdjusted,
      'fieldGoalsAttempted': instance.fieldGoalsAttempted,
      'fieldGoalsPercentage': instance.fieldGoalsPercentage,
      'foulsOffensive': instance.foulsOffensive,
      'foulsPersonal': instance.foulsPersonal,
      'foulsDrawn': instance.foulsDrawn,
      'foulsTeam': instance.foulsTeam,
      'foulsTechnical': instance.foulsTechnical,
      'foulsTeamTechnical': instance.foulsTeamTechnical,
      'freeThrowsAttempted': instance.freeThrowsAttempted,
      'freeThrowsMade': instance.freeThrowsMade,
      'freeThrowsPercentage': instance.freeThrowsPercentage,
      'leadChanges': instance.leadChanges,
      'minutes': instance.minutes,
      'minutesCalculated': instance.minutesCalculated,
      'points': instance.points,
      'pointsAgainst': instance.pointsAgainst,
      'pointsFastBreak': instance.pointsFastBreak,
      'pointsFromTurnovers': instance.pointsFromTurnovers,
      'pointsInThePaint': instance.pointsInThePaint,
      'pointsInThePaintMade': instance.pointsInThePaintMade,
      'pointsInThePaintAttempted': instance.pointsInThePaintAttempted,
      'pointsInThePaintPercentage': instance.pointsInThePaintPercentage,
      'pointsSecondChance': instance.pointsSecondChance,
      'reboundsDefensive': instance.reboundsDefensive,
      'reboundsPersonal': instance.reboundsPersonal,
      'reboundsOffensive': instance.reboundsOffensive,
      'reboundsTeam': instance.reboundsTeam,
      'reboundsTeamOffensive': instance.reboundsTeamOffensive,
      'reboundsTeamDefensive': instance.reboundsTeamDefensive,
      'reboundsTeamTotal': instance.reboundsTeamTotal,
      'secondChancePointsAttempted': instance.secondChancePointsAttempted,
      'secondChancePointsMade': instance.secondChancePointsMade,
      'secondChancePointsPercentage': instance.secondChancePointsPercentage,
      'steals': instance.steals,
      'threePointersMade': instance.threePointersMade,
      'threePointersPercentage': instance.threePointersPercentage,
      'threePointersAttempted': instance.threePointersAttempted,
      'timeLeading': instance.timeLeading,
      'timesTied': instance.timesTied,
      'trueShootingAttempts': instance.trueShootingAttempts,
      'trueShootingPercentage': instance.trueShootingPercentage,
      'turnovers': instance.turnovers,
      'turnoversTeam': instance.turnoversTeam,
      'turnoversTotal': instance.turnoversTotal,
      'twoPointersMade': instance.twoPointersMade,
      'twoPointersAttempted': instance.twoPointersAttempted,
      'twoPointersPercentage': instance.twoPointersPercentage,
    };
